"""
Extract ZIP entries from cleaned DOCX templates into separate TypeScript data files.
Each template gets its own file to keep function bundle sizes under 1MB.
"""
import os, sys, zipfile, base64

TEMPLATES_DIR = r"D:\myproject\darling-dupe-maker\_templates_cleaned"
OUT_DIR = r"D:\myproject\darling-dupe-maker\functions\api"

def extract_docx_to_b64(path):
    entries = {}
    with zipfile.ZipFile(path, 'r') as zf:
        for name in zf.namelist():
            data = zf.read(name)
            entries[name] = base64.b64encode(data).decode('ascii')
    return entries

templates = {}
for fname in sorted(os.listdir(TEMPLATES_DIR)):
    if fname.endswith('.docx'):
        name = fname.replace('.docx', '').lower().replace(' ', '_')
        path = os.path.join(TEMPLATES_DIR, fname)
        templates[name] = extract_docx_to_b64(path)
        print(f"{fname}: {len(templates[name])} entries, " +
              f"total b64: {sum(len(v) for v in templates[name].values()):,} chars")

# Generate separate files
for tname, entries in templates.items():
    var_name = "_" + tname
    out_path = os.path.join(OUT_DIR, f"_template_{tname}.ts")
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(f"// Auto-generated template data for {tname}\n")
        f.write(f"// Generated by _extract_register_templates.py — DO NOT EDIT\n\n")
        f.write(f"const {var_name}: Record<string, string> = {{\n")
        for name in sorted(entries.keys()):
            b64 = entries[name]
            f.write(f'  "{name}": "{b64}",\n')
        f.write("};\n\n")
        f.write(f"export default {var_name};\n")
    size = os.path.getsize(out_path)
    print(f"  → {os.path.basename(out_path)}: {size:,} bytes")

print(f"\nDone! Generated {len(templates)} files in {OUT_DIR}")
