
-- Bulk data import: officer and shareholder details from RTF files
-- This updates addresses, ID numbers, dates for all officers and shareholders

-- Officers: Ableland (667527)
UPDATE officers SET address = 'OMC CHAMBERS, P.O. BOX 3152, ROAD TOWER, BRITISH VIRGIN ISLANDS', date_appointed = '19/10/2005', date_ceased = '25/05/2009', identity = 'corporate' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '667527') AND name_english ILIKE 'PRIMEBASE INVESTMENT LIMITED%';
UPDATE officers SET address = '34B, 2/F, YUEN KONG SAN CHUEN, KAM SHEUNG ROAD, PAT HEUNG, YUEN LONG, NEW TERRITORIES, HONG KONG', id_number = 'G110332(5)', date_appointed = '25/05/2009', date_ceased = '20/07/2009' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '667527') AND name_english ILIKE 'WONG, WILLIAM%';
UPDATE officers SET address = 'OMC CHAMBERS, P.O. BOX 3152, ROAD TOWER, BRITISH VIRGIN ISLANDS', date_appointed = '20/07/2009', place_incorporated = 'BRITISH VIRGIN ISLANDS', company_number_ref = '643231', identity = 'corporate' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '667527') AND name_english ILIKE 'WORLDSHINE LIMITED%';
UPDATE officers SET address = '6/F., HECNY TOWER, 9 CHATHAM ROAD SOUTH, TSIM SHA TSUI, KOWLOON, HONG KONG', date_appointed = '15/07/2005', company_number_ref = '789826', identity = 'corporate' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '667527') AND name_english ILIKE 'WORLDWIDE INCORPORATION NETWORK LIMITED%';

-- Shareholders: Ableland (667527)  
UPDATE shareholders SET address = '6/F., HECNY TOWER, 9 CHATHAM ROAD SOUTH, TSIM SHA TSUI, KOWLOON, HONG KONG', share_type = 'ORD - USD1.00 ORDINARY FULLY PAID (USD)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '667527') AND (name ILIKE '%SMARTCOM SECRETARIES LIMITED%' OR name_english ILIKE '%SMARTCOM SECRETARIES LIMITED%');
UPDATE shareholders SET address = 'VISTRA CORPORATE SERVICES CENTRE, SECOND FLOOR, THE QUADRANT, MANGLIER STREET, VICTORIA, MAHE, REPUBLIC OF SEYCHELLES', share_type = 'ORD - USD1.00 ORDINARY FULLY PAID (USD)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '667527') AND (name ILIKE '%TWINSAIL LIMITED%' OR name_english ILIKE '%TWINSAIL LIMITED%');

-- Officers: AGF (2030762)
UPDATE officers SET address = 'NO 27, JLN PUNCAK SETIAWANGSA 6, TMN SETIWANGSA, 54200 KUALA LUMPUR, MALAYSIA', id_number = 'A53147147', date_appointed = '22/01/2020' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2030762') AND name_english ILIKE 'HASAN AZIZ, SHAHRIL ANAS%';
UPDATE officers SET address = 'RM D, 10/F, TOWER ONE, METRO CITY, PHASE 2, TSEUNG KWAN O, NEW TERRITORIES, HONG KONG', id_number = 'E500635(3)', date_appointed = '22/01/2020' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2030762') AND name_english ILIKE 'LUI, CHI KEUNG%';
UPDATE officers SET address = 'HOUSE C12, VILLE DE JARDIN, 33-35 SUI WO ROAD, FOTAN, SHATIN, NEW TERRITORIES, HONG KONG', id_number = 'G300388(3)', date_appointed = '22/01/2020' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2030762') AND name_english ILIKE 'NGAI, MING TAK%';
UPDATE officers SET address = 'FLAT H, 50/F, TOWER 1, QUEEN''S TERRACE, NO 1 QUEEN STREET, HONG KONG', id_number = 'R788688(7)', date_appointed = '22/01/2020' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2030762') AND name_english ILIKE 'ZHU, ZHANGJIN%';
UPDATE officers SET address = 'ROOM 405 TUNG NING BUILDING, 249-253 DES VOEUX ROAD CENTRAL, SHEUNG WAN, HONG KONG', identity = 'corporate', place_incorporated = 'HONG KONG', company_number_ref = '124806' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2030762') AND name_english ILIKE 'TWINSAIL CONSULTANTS LIMITED%';

-- Officers: 1&1 Food (2325874)
UPDATE officers SET address = 'FLAT 1608, 16/F., TAK SHAN HOUSE, TAK LONG ESTATE, KOWLOON CITY, KOWLOON, HONG KONG', id_number = 'P373848(9)', date_appointed = '01/01/2016' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2325874') AND name_english ILIKE 'AU KWOK LAM%';
UPDATE officers SET address = 'FLAT 1015, SHEK ON HOUSE, 8 WAI KEK STREET, SHEK LEI ESTATE, KWAI CHUNG, NEW TERRITORIES, HONG KONG', id_number = 'K895142(A)', date_appointed = '01/01/2016' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2325874') AND name_english ILIKE 'LEUNG YUK WA%';
UPDATE officers SET id_number = 'K705092(5)', date_appointed = '01/01/2016' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2325874') AND name_english ILIKE 'SO KWONG MING%';
UPDATE officers SET address = 'ROOM 405 TUNG NING BUILDING, 249-253 DES VOEUX ROAD CENTRAL, SHEUNG WAN, HONG KONG', date_appointed = '01/01/2016', identity = 'corporate', place_incorporated = 'HONG KONG', company_number_ref = '124806' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2325874') AND name_english ILIKE 'TWINSAIL CONSULTANTS LIMITED%';

-- Shareholders: 1&1 Food (2325874)
UPDATE shareholders SET address = 'FLAT 1608, 16/F., TAK SHAN HOUSE, TAK LONG ESTATE, KOWLOON CITY, KOWLOON, HONG KONG', share_type = 'ORD - HK$1.00 ORDINARY FULLY PAID (HK$)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2325874') AND (name ILIKE '%AU KWOK LAM%' OR name_english ILIKE '%AU KWOK LAM%');
UPDATE shareholders SET address = 'FLAT 1015, SHEK ON HOUSE, 8 WAI KEK STREET, SHEK LEI ESTATE, KWAI CHUNG, NEW TERRITORIES, HONG KONG', share_type = 'ORD - HK$1.00 ORDINARY FULLY PAID (HK$)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2325874') AND (name ILIKE '%LEUNG YUK WA%' OR name_english ILIKE '%LEUNG YUK WA%');
UPDATE shareholders SET address = 'G/F, 4 SAN SHEK WAN VILLAGE PHRASE I, SAN SHEK WAN, TUEN MUN, NEW TERRITORIES, HONG KONG', share_type = 'ORD - HK$1.00 ORDINARY FULLY PAID (HK$)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2325874') AND (name ILIKE '%SO KWONG MING%' OR name_english ILIKE '%SO KWONG MING%');

-- Officers: ACM Trading (2158285)
UPDATE officers SET address = 'ROOM B, 18TH FLOOR, BLOCK 2, YUE SUN MANSION, 89 THIRD STREET, SAI YING PUN, HONG KONG', id_number = 'P183291(7)', date_appointed = '21/10/2014' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2158285') AND name_english ILIKE 'MA AYE AYE KHINE%';
UPDATE officers SET address = 'ROOM 405 TUNG NING BUILDING, 249-253 DES VOEUX ROAD CENTRAL, SHEUNG WAN, HONG KONG', date_appointed = '21/10/2014', identity = 'corporate', place_incorporated = 'HONG KONG', company_number_ref = '124806' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2158285') AND name_english ILIKE 'TWINSAIL CONSULTANTS LIMITED%';

-- Shareholders: ACM Trading (2158285)
UPDATE shareholders SET address = 'ROOM B, 18TH FLOOR, BLOCK 2, YUE SUN MANSION, 89 THIRD STREET, SAI YING PUN, HONG KONG', share_type = 'ORD - HK$1.00 ORDINARY FULLY PAID (HK$)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2158285') AND (name ILIKE '%MA AYE AYE KHINE%' OR name_english ILIKE '%MA AYE AYE KHINE%');

-- Officers: ANI Sports (1034651)
UPDATE officers SET address = 'FLAT B, 4/F, VIENNA MANSION, 55 PATERSON STREET, CAUSEWAY BAY, HONG KONG', id_number = 'Z015630(3)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '1034651') AND name_english ILIKE 'JIE ELYNI%';
UPDATE officers SET address = 'ROOM 405 TUNG NING BUILDING, 249-253 DES VOEUX ROAD CENTRAL, SHEUNG WAN, HONG KONG', date_appointed = '29/03/2006', identity = 'corporate', place_incorporated = 'HONG KONG', company_number_ref = '124806' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '1034651') AND name_english ILIKE 'TWINSAIL CONSULTANTS LIMITED%';
UPDATE shareholders SET address = 'FLAT B, 4/F, VIENNA MANSION, 55 PATERSON STREET, CAUSEWAY BAY, HONG KONG', share_type = 'ORD - HK$1.00 ORDINARY FULLY PAID (HK$)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '1034651') AND (name ILIKE '%JIE ELYNI%' OR name_english ILIKE '%JIE ELYNI%');

-- Officers: ATR (713366)
UPDATE officers SET id_number = 'A869409(8)', address = '香港仔中心海瑩閣21樓4號室, HONG KONG' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '713366') AND name_english ILIKE 'KO KAM WAI%';
UPDATE officers SET address = 'ROOM 23D, 23/F., HONGLING BUILDING, HONGLING ROAD, SHENZHEN, CHINA', id_number = '420922590506009', date_appointed = '19/04/2000' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '713366') AND name_english ILIKE 'YANG XIAOGANG%';
UPDATE officers SET address = 'ROOM 1812, 18/F., LIJING BUILDING, HONGLING ZHONG ROAD, SHENZHEN, CHINA', id_number = '330106670422005', date_appointed = '19/04/2000', date_ceased = '10/10/2011' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '713366') AND name_english ILIKE 'YU LIDONG%';
UPDATE officers SET address = 'ROOM 1812, LIKING BUILDING, 1008 HONG LING ROAD, LOWU, SHENZHEN, CHINA', id_number = '510102197008118469', date_appointed = '19/04/2000' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '713366') AND name_english ILIKE 'ZENG YI%';

-- Officers: ACTminton (3045009)
UPDATE officers SET address = 'FLAT B, 4/F, VIENNA MANSION, 55 PATERSON STREET, CAUSEWAY BAY, HONG KONG', id_number = 'Z015630(3)', date_appointed = '04/05/2021' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '3045009') AND name_english ILIKE 'JIE ELYNI%';
UPDATE officers SET address = 'ROOM 405 TUNG NING BUILDING, 249-253 DES VOEUX ROAD CENTRAL, SHEUNG WAN, HONG KONG', date_appointed = '04/05/2021', identity = 'corporate', place_incorporated = 'HONG KONG', company_number_ref = '124806' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '3045009') AND name_english ILIKE 'TWINSAIL CONSULTANTS LIMITED%';

-- Company 0073430 officers
UPDATE officers SET address = 'ROOM 706, BLOCK H, TELFORD GARDEN, KOWLOON BAY, KOWLOON, HONG KONG', id_number = 'K936929(5)', date_appointed = '18/11/2021' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND name_english ILIKE 'CHAN ADRIAN HIU TUNG%';
UPDATE officers SET address = 'ROOM 706, BLOCK H, TELFORD GARDEN, KOWLOON BAY, KOWLOON, HONG KONG', id_number = 'E407502(5)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND name_english ILIKE 'CHAN HON PONG DAVID%';
UPDATE officers SET address = 'FLAT 5G, 5/F, BLOCK 12, YEE MOON COURT, SOUTH HORIZONS PHASE 2, AP LEI CHAU, HONG KONG', id_number = 'E314964(5)', date_appointed = '16/02/2021' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND name_english ILIKE 'CHAN WAI MING WINNIE%';
UPDATE officers SET address = '7/F., MEI FOO SUN CHUEN, 44B NASSAU STREET, KOWLOON, HONG KONG', id_number = 'B504582(2)', date_appointed = '30/09/2016' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND name_english ILIKE 'IP WAI HEY%';
UPDATE officers SET address = '12A BLOCK 4 TANNER GARDEN, TANNER ROAD NORTH POINT, HONG KONG', id_number = 'G093111(9)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND name_english ILIKE 'KAM FUNG HA KARIN%';
UPDATE officers SET id_number = 'E742521(3)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND name_english ILIKE 'LI HEI MAN%';
UPDATE officers SET address = 'M/F, 42 TIN HAU TEMPLE ROAD, NORTH POINT, HONG KONG', id_number = 'D857251(9)', date_appointed = '01/12/2021' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND name_english ILIKE 'TANG LEON WAI SHUN%';
UPDATE officers SET address = 'ROOM 405 TUNG NING BUILDING, 249-253 DES VOEUX ROAD CENTRAL, SHEUNG WAN, HONG KONG', id_number = 'A628830(0)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND name_english ILIKE 'TANG SIU FAN%';
UPDATE officers SET address = '12/F, HARITA COURT, 199A PRINCE EDWARD ROAD WEST, KOWLOON, HONG KONG', id_number = 'E961968(6)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND name_english ILIKE 'TONG  WING FUNG ERIC%';
UPDATE officers SET address = '12/F., HARITA COURT, 199A PRINCE EDWARD ROAD WEST, KOWLOON, HONG KONG', id_number = 'B160133(A)', date_appointed = '25/09/1979', date_ceased = '28/11/2019' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND name_english ILIKE 'TONG SHIU WING%';
UPDATE officers SET identity = 'corporate', place_incorporated = 'HONG KONG', company_number_ref = '0577938', address = 'ROOM 405 TUNG NING BUILDING, 249-253 DES VOEUX ROAD CENTRAL, SHEUNG WAN, HONG KONG' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND name_english ILIKE 'ASIAN GLORY INTERNATIONAL%';
UPDATE officers SET identity = 'corporate', place_incorporated = 'HONG KONG', company_number_ref = '98503', address = 'ROOM 1407 OI WAH COURT, TZE COURT STAGE 3 TZE WAN SHAN, KOWLOON, HONG KONG', date_appointed = '23/05/2019' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND name_english ILIKE 'TIM FUNG STEAM LAUNDRY%';

-- Company 0073430 shareholders
UPDATE shareholders SET address = 'ROOM 706, BLOCK H, TELFORD GARDEN, KOWLOON BAY, KOWLOON, HONG KONG', share_type = 'ORD - HK$100.00 ORDINARY FULLY PAID (HK$)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND (name ILIKE '%CHAN ADRIAN HIU TUNG%' OR name_english ILIKE '%CHAN ADRIAN HIU TUNG%');
UPDATE shareholders SET address = '7/F., MEI FOO SUN CHUEN, 44B NASSAU STREET, KOWLOON, HONG KONG', share_type = 'ORD - HK$100.00 ORDINARY FULLY PAID (HK$)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND (name ILIKE '%IP WAI HEY%' OR name_english ILIKE '%IP WAI HEY%');
UPDATE shareholders SET address = '12A BLOCK 4 TANNER GARDEN, TANNER ROAD NORTH POINT, HONG KONG', share_type = 'ORD - HK$100.00 ORDINARY FULLY PAID (HK$)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND (name ILIKE '%KAM FUNG HA KARIN%' OR name_english ILIKE '%KAM FUNG HA KARIN%');
UPDATE shareholders SET address = 'ROOM 1407 OI WAH COURT, TZE COURT STAGE 3 TZE WAN SHAN, KOWLOON, HONG KONG', share_type = 'ORD - HK$100.00 ORDINARY FULLY PAID (HK$)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND (name ILIKE '%LI HEI MAN%' OR name_english ILIKE '%LI HEI MAN%');
UPDATE shareholders SET address = 'ROOM 405 TUNG NING BUILDING, 249-253 DES VOEUX ROAD CENTRAL, SHEUNG WAN, HONG KONG', share_type = 'ORD - HK$100.00 ORDINARY FULLY PAID (HK$)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND (name ILIKE '%SMART GAIN INVESTMENTS%' OR name_english ILIKE '%SMART GAIN INVESTMENTS%');
UPDATE shareholders SET address = '12/F, HARITA COURT, 199A PRINCE EDWARD ROAD, KOWLOON, HONG KONG', share_type = 'ORD - HK$100.00 ORDINARY FULLY PAID (HK$)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0073430') AND (name ILIKE '%TONG  WING FUNG ERIC%' OR name_english ILIKE '%TONG  WING FUNG ERIC%');

-- Company 0121727
UPDATE officers SET address = 'FLAT E, 32/F, BLOCK 9, METRO CITY PHASE II, TSUENG KWAN O, HONG KONG', id_number = 'H317594(6)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0121727') AND name_english ILIKE 'HUI MAN HOI%';
UPDATE officers SET address = 'FLAT A, 18/F, GARVE COURT, PERTH GARDEN, 9 PERTH STREET, HO MAN TIN, HONG KONG', id_number = 'E375390(9)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0121727') AND name_english ILIKE 'LEE KWOK BUN KEVIN%';
UPDATE officers SET address = 'UNIT 3312, 33/F, SHUI ON CENTRE, 6-8 HARBOUR ROAD, WANCHAI, HONG KONG', identity = 'corporate', place_incorporated = 'HONG KONG', company_number_ref = '011227' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0121727') AND name_english ILIKE 'NORCOLA COMPANY LIMITED%';
UPDATE shareholders SET address = 'FLAT A, 18/F, GARVE COURT, PERTH GARDEN, 9 PERTH STREET, HO MAN TIN, HONG KONG', share_type = 'ORD - HK$1.00 ORDINARY FULLY PAID (HK$)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '0121727') AND (name ILIKE '%LEE KWOK BUN KEVIN%' OR name_english ILIKE '%LEE KWOK BUN KEVIN%');
