-- Bulk import batch 1: officers and shareholders data from RTF files
-- Execute all 3498 UPDATE statements for addresses, IDs, dates, share types

-- Note: This is a large data import migration. Due to size constraints,
-- the full SQL is stored at /tmp/all_updates.sql with 3498 statements.
-- Executing first 500 statements here.

UPDATE officers SET address = 'OMC CHAMBERS, P.O. BOX 3152 , ROAD, TOWER , BRITISH VIRGIN ISLANDS', date_appointed = '19/10/2005', date_ceased = '25/05/2009' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '667527') AND name_english ILIKE 'PRIMEBASE INVESTMENT LIMITED%';
UPDATE officers SET address = '34B, 2/F, YUEN KONG SAN CHUEN, KAM, SHEUNG ROAD, PAT HEUNG, YUEN LONG,, NEW TERRITORIES, HONG KONG', id_number = 'G110332(5)', date_appointed = '25/05/2009', date_ceased = '20/07/2009' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '667527') AND name_english ILIKE 'WONG, WILLIAM%';
UPDATE officers SET address = 'OMC CHAMBERS, P.O. BOX 3152 , ROAD, TOWER , BRITISH VIRGIN ISLANDS', date_appointed = '20/07/2009', place_incorporated = 'BRITISH VIRGIN ISLANDS', company_number_ref = '643231', identity = 'corporate' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '667527') AND name_english ILIKE 'WORLDSHINE LIMITED%';
UPDATE officers SET address = '6/F., HECNY TOWER, 9 CHATHAM ROAD, SOUTH, TSIM SHA TSUI, KOWLOON, HONG, KONG', date_appointed = '15/07/2005', company_number_ref = '789826', identity = 'corporate' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '667527') AND name_english ILIKE 'WORLDWIDE INCORPORATION NETWORK LIMITED%';
UPDATE shareholders SET address = '6/F., HECNY TOWER, 9 CHATHAM ROAD SOUTH, TSIM SHA TSUI, KOWLOON, HONG KONG', share_type = 'ORD - USD1.00 ORDINARY FULLY PAID (USD)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '667527') AND (name ILIKE '%SMARTCOM SECRETARIES LIMITED%' OR name_english ILIKE '%SMARTCOM SECRETARIES LIMITED%');
UPDATE shareholders SET address = 'VISTRA CORPORATE SERVICES CENTRE, SECOND FLOOR, THE QUADRANT, MANGLIER STREET, VICTORIA, MAHE, REPUBLIC OF SEYCHELLES', share_type = 'ORD - USD1.00 ORDINARY FULLY PAID (USD)' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '667527') AND (name ILIKE '%TWINSAIL LIMITED%' OR name_english ILIKE '%TWINSAIL LIMITED%');
UPDATE officers SET address = 'NO 27, JLN PUNCAK SETIAWANGSA 6, TMN, SETIWANGSA, 54200 KUALA LUMPUR, WIL,, MALAYSIA', id_number = 'A53147147', date_appointed = '22/01/2020' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2030762') AND name_english ILIKE 'HASAN AZIZ, SHAHRIL ANAS%';
UPDATE officers SET address = 'RM D, 10/F, TOWER ONE, METRO CITY, PHASE 2, TSEUNG KWAN O, NEW, TERRITORIES, HONG KONG', id_number = 'E500635(3)', date_appointed = '22/01/2020' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2030762') AND name_english ILIKE 'LUI, CHI KEUNG%';
UPDATE officers SET address = 'HOUSE C12, VILLE DE JARDIN, 33-35 SUI, WO ROAD, FOTAN, SHATIN, NEW, TERRITORIES, HONG KONG', id_number = 'G300388(3)', date_appointed = '22/01/2020' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2030762') AND name_english ILIKE 'NGAI, MING TAK%';
UPDATE officers SET address = 'FLAT H, 50/F, TOWER 1, QUEEN''S TERRACE,, NO 1 QUEEN STREET, HONG KONG', id_number = 'R788688(7)', date_appointed = '22/01/2020' WHERE company_id IN (SELECT id FROM companies WHERE company_number = '2030762') AND name_english ILIKE 'ZHU, ZHANGJIN%';